language: julia

os:
  - linux

julia:
  - 1.1
  - nightly

addons:
  apt:
    packages:
      - python3-matplotlib

env:
  matrix:
    - PYTHON=python3

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

after_success:
  - julia -e 'Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

notifications:
  email: false
