language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

after_success:
  - julia -e 'import MLToolkit;
              cd(joinpath(dirname(pathof(MLToolkit)), "..", paths...));
              Pkg.add("Coverage");
              using Coverage;
              Coveralls.submit(process_folder())'
