name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();'
      - name: Build dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.build();'
      - name: Build MLToolkit
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs --color=yes docs/make.jl
